### PR TITLE
Micro-Reddit clone

### PR DESCRIPTION
**Pull request by elyor-doniyorov**
To build this project, we:
-use Rails associations, validations
-use code linters
-use Rails active records

### CODE REVIEW

**Review by smcommits — COMMENTED** [review]
# Status: Invalid 🛑 

## Hello, @elyor-doniyorov! Thank you so much for all your hard work. Your efforts are highly appreciated. Unfortunately, as your linter checks are failing, this PR has been marked as invalid. Please make sure that all your linter checks are green before requesting the review. Good Luck. 

# 

#### Please reach out to me on Slack if you need any assistance.

**Comment by elyor-doniyorov** [comment]
Last error is fixed now. Thanks for your review

**Comment by smcommits** [comment]
@elyor-doniyorov Great! Please request another review from your dashboard.

**Review by henatan99 — CHANGES_REQUESTED** [review]
# Changes Requested :recycle: 

Hi there, nice work so far. There are some improvements to make before your project gets approved. 

## To Highlight 
- Models and associations are working fine
- Proper migration files are generated 

## To Improve
- It is a mandatory requirement to have a descriptive readme. Please refer to the link below and make the necessary changes!
[General Requirements](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/) 
[Readme Template](https://github.com/microverseinc/readme-template) 

- Add foreign_key constraint to your post model as it guarantees referential integrity. You can generate a migration file and fill it manually as the tips shown below:
   step 1: run $ rails g migration AddUserIdForeignKeyToPost
   step 2: Open the migration file and edit it as 
     ```
         class AddUserIdForeignKeyToPost < ActiveRecord::Migration[6.1]
             def change
                   add_foreign_key :posts, :users
             end
         end
    ```
   Step 3: run $ rails db:migrate
### Kindly make the requested changes and submit for another review

If you want to contact me you can find me via:
[LinkedIn](https://www.linkedin.com/in/henok-mekonnen/) | [Twitter](https://twitter.com/henatan99) | Henok Mekonnen on Slack 

## Happy Coding :computer:

**Review by smcommits — APPROVED** [review]
# Status: Approved 👍🏽 

## Hello, @elyor-doniyorov! You have done a great job. The application appears to be fantastic. Excellent work implementing the changes that the previous reviewer requested. This PR is now approved. You can go ahead and merge the branch. Congratulations and good luck.

**Comment by elyor-doniyorov** [comment]
Thank you!

**Pull request merged**
